### ISSUE TITLE
Tests are currently using db and not entity

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#13]
Refactor https://github.com/nerdstein/encrypt/tree/master/src/Tests

**Comment by nerdstein** [comment]
Can you eval the tests now that the arch is more straight forward?

The tests should be per plugin. Should set the settings with a specific key, should return the same output. 

Test encrypt and decrypt for all plugins

**Comment by mjl3475** [comment]
Next Steps: Set up a manual test to check whether encryption and decryption work. Then port test to a simpletest.

**Comment by nerdstein** [comment]
Potential test:
-Dependency to key
-Create a SimpleKey type with contents
-Update EncryptSettingsForm, pick predetermined key and type
-Invoke \Drupal::get('encryption')->encrypt with predetermined text, test result
-Invoke \Drupal::get('encryption')->decrypt with predetermined text, test result

**Comment by nerdstein** [comment]
PR: https://github.com/nerdstein/encrypt/pull/32

**Comment by nerdstein** [comment]
Reopening - need to look at other tests besides EncryptService

**Comment by nerdstein** [comment]
We need tests per plugin.

**Comment by nerdstein** [comment]
Tests are failing in Travis now. I need some help looking at this.

**Comment by rlhawk** [comment]
Closing this. See #77.
