### ISSUE TITLE
Does D8 use help.ini?

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#17]
https://github.com/nerdstein/encrypt/blob/master/help/encrypt.help.ini

Not sure this is to be used. Is this correct?

**Comment by mjl3475** [comment]
help.ini is used by https://www.drupal.org/project/advanced_help

We should postpone updating this part until we finish the module and maybe until there is a stable advanced_help module.

**Comment by nerdstein** [comment]
Assigned to you to look at/implement. No rush, low prio

**Comment by rlhawk** [comment]
Closing this; we'll revisit it once the module is back on Drupal.org.
