### ISSUE TITLE
 Should the Encryption Service allow for using a non-default encryption configuration?

### ISSUE THREAD

**Issue by mjl3475** [d8-contrib-modules/encrypt#25]
$->encrypt($text, $encryptionMethod, $keyType);

**Comment by nerdstein** [comment]
Overloaded encrypt function that passes a method and system key? Key != KeyType

**Comment by nerdstein** [comment]
One challenge to this approach is the specific encryption method settings. Our current plan is to build a settings form per plugin which is exposed to the EncryptSettingsForm. 

To be able to do this, we would need instances of the encryption method that already have the settings built in. The proposed overloaded function doesn't have settings, and this would likely require the use of a separate "EntityProfile" entity. Putting this on hold until we see if we need it.

**Comment by nerdstein** [comment]
We need to add a new service endpoint to pull in any encryption type.

**Comment by nerdstein** [comment]
Current feature set: service->encrypt($text) and service->decrypt($text);

New feature:
service->encrypt($text, $enc_method, $key_type) and service->decrypt($text, $enc_method, $key_type)
