### ISSUE TITLE
Rename "Configuration" to "Profile"

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#27]
When I originally wrote the existing system for managing bundles of encryption settings, I used the label "configuration" to refer to them. Since that term has a specific meaning within Drupal 8, we should consider changing it to "profile."

**Comment by nerdstein** [comment]
@rlhawk - this was cruft from an automated Drupal Module Porter that Matt initially used. The concept of "Configuration" has been removed in lieu of a SettingsForm.

We merged in that PR earlier, so you can now see the updates.

This begs the question about the current architecture. Currently, we only have the SettingsForm, which is similar to a globally selected Encryption Method and a globally selected Key. The concept of the "Profiles" has been replaced by one global option that the Encryption service leverages for it's behaviors. Does this make sense?

**Comment by rlhawk** [comment]
Having just a single settings form is a big step backward for the module. Version 1 had global settings; version 2 added  support for configurations/profiles, which I think enhances the module quite a bit.

**Comment by nerdstein** [comment]
Related to issue #25

**Comment by nerdstein** [comment]
One idea: service->encrypt($text, $enc_method, $key_type) and service->decrypt($text, $enc_method, $key_type)

**Comment by nerdstein** [comment]
This is done
