### ISSUE TITLE
Ensure that Encryption method dependencies are met

### ISSUE THREAD

**Issue by mjl3475** [d8-contrib-modules/encrypt#34]
Ensure that Encryption method dependencies are met before they can be used. This should probably take place on the settings form when the item is selected or on the form validate.

**Comment by nerdstein** [comment]
Requirements of contrib/submodules with plugins

**Comment by nerdstein** [comment]
One specific case:

We need mcrypt submodule with requirements baked in. Need this logic built in

**Comment by nerdstein** [comment]
This is now moved to the Encryption Profile UI through the Encryption Method.

The "bridge" should be key-based requirements, like 16-bit, 24-bit, or 32-bit keys.

We need to extend the Key module to expose which requirements a key meets. Then we need to integrate this in with Encrypt for the Encryption Profile UI

**Comment by svendecabooter** [comment]
The current validate() method on the EncryptionProfile entity, as well as the checkDependencies() method on EncryptionMethod plugins seem to cover this issue.

Please reopen if you feel this has not been properly covered in the current codebase.
