### ISSUE TITLE
EncryptService Test assumes mcrypt PHP module is installed.

### ISSUE THREAD

**Issue by mjl3475** [d8-contrib-modules/encrypt#35]
We may want to wrap the test in if (!function_exists('mcrypt_encrypt')) {} and output a message that the php module isn't installed if it fails.

**Comment by nerdstein** [comment]
Related to issue #34 and will be resolved by mcrypt submodule

**Comment by rlhawk** [comment]
Closing this, since the Mcrypt encryption method will be removed from the project soon.
