### ISSUE TITLE
Create a test page and drush command to be able test Encryption

### ISSUE THREAD

**Issue by mjl3475** [d8-contrib-modules/encrypt#38]
Page just has a text field to encrypt and decrypt text. Let you easily test out your key and encryption method configuration.

The same would apply for the drush comand just without the UI `drush encryption encrypt "Test"` and `drush encryption decrypt "avv9wervwen!d"`

**Comment by rlhawk** [comment]
I like this idea a lot. I'll leave this issue open, even though it may not be implemented before development is moved to Drupal.org.

**Comment by svendecabooter** [comment]
PR submitted to add this functionality

**Comment by svendecabooter** [comment]
This functionality has been added to master now. Closing issue.
