### ISSUE TITLE
Evaluate design of EncryptionMethod plugin type

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#4]
Use case: mcrypt. Consider either separate plugin types or one plugin type with the settings below.

-Separate submodule of Encrypt
-mcrypt plugin type
-look at cyphers (aes, rjindal, blowfish)
-look at mode (cbc)

**Comment by nerdstein** [comment]
Keeping this open to eval as part of ongoing review

**Comment by nerdstein** [comment]
Per convo over Slack, remove current mcrypt plugins. Replace with one Mcrypt plugin with settings for cipher and options. Depends on issue #7 wrapping up

**Comment by rlhawk** [comment]
I propose that a base MCrypt plugin is created, which can be extended by sub-plugins to support various configurations of cipher and mode. Certain ciphers only support certain modes and vice versa, and both have different requirements for block size, key length, etc., so it's not really practical to allow choosing them through a settings form.

**Comment by rlhawk** [comment]
The MCrypt configuration that we should include by default (and encourage) should employ some variation of Rijndael, along with CBC for the mode.

**Comment by nerdstein** [comment]
@rlhawk. Matt and I were chatting. We're going to work in pieces here and build up step by step.

In short, we're going to start by extending plugins to have their own settings forms. This provides custom logic for the form, the form validation, and submit handling per plugin.

For now, we will bake this into the EncryptSettingsForm via AJAX after selecting the encryption method (aka plugin).

My only concern right now is that the Key is global to the EncryptionSettings. It's not tied to the EncryptionMethod yet. We need to discuss this thereafter.

**Comment by nerdstein** [comment]
Good for now and will revisit later
