### ISSUE TITLE
Create PHPUnit tests

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#41]

**Comment by nerdstein** [comment]
@adweingarten - care to take a stab?

**Comment by nerdstein** [comment]
Will need to uncomment PHPUnit from Travis test

**Comment by svendecabooter** [comment]
Thanks to review and comment on my pull request, that adds PHPUnit tests, and does some refactoring to make the code more testable and adhering to D8 & general PHP best practices.

**Comment by svendecabooter** [comment]
PHPUnit tests are now up to date with the codebase, and method that deserve proper testing, have test coverage now.

We should continue updating the unit tests when functionality changes, but that should be handled in the future issues themselves, so marking this one as done.
