### ISSUE TITLE
Allow encrypt module to support multiple encryption instances

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#47]
1. Change encrypt settings UI to support creation of multiple instances (open to CMI)
2. Ability to set "default" global encryption instance for the service
3. Extend the service to be able to specify an instance and not just the default
->encryptWithInstance($inst, $string), ->decryptWithInstance($inst, $string)
4. Validate that machine names/IDs are unique to each encrypt service

**Comment by nerdstein** [comment]
Need a "getInstances()" for encrypt service

**Comment by nerdstein** [comment]
Idea: a module can ship via CMI with an instance

**Comment by nerdstein** [comment]
@damontgomery will this help support the needs for field encrypt?

**Comment by damontgomery** [comment]
@nerdstein maybe it would help if you could walk me through it.

I can see two options, maybe this is what you're talking about.

## Simple Option
Create an encryption plugin type EncryptionPlugin. This will have everything it needs and no configuration is allowed. This way if you need to provide a key, the key module would have to define which key to use, you couldn't change it for different encryption uses like fields etc. They'd all have to be the same.

Then field_encrypt can just reference the plugins in the mapping I made and you just need to provide a plugin manager which can be modeled after the blocks one.

This one is simpler for everyone but more limited.

## Complex Option
More or less mirroring how blocks works. You have a plugin type (EncryptionPlugin) and a config entity type (EncryptionEntity).

MyEncryptionPlugin implements EncryptionPluginInterface

The Encryption plugin defines the basic methods. The config entity is associated with specific plugins but has other information like keys, etc. I'm not too familiar with it, maybe @EclipseGc could help here.

You can provide a default EncryptionEntity that uses a default pattern in /config with YML. Drupal console can help scaffold the UI for managing the config entities.

From there, the Site Builder would need to select a EncryptionEntity for each field they want to use which would make using field_encrypt more difficult. But, this way you could use one key for one field and another for another field.

**Comment by damontgomery** [comment]
I think your method `encryptWithInstance()` implies that you can either use an instance or not and I think that's a confusing pattern. I'd pick one method and make everything use it. There are already systems for managing plugins / config entities, so I don't think we should create weird in-betweens for this specific module. If you want it to be flexible, you always have to load a specific method.

I'd like to see in some way,

```
$encrypted_value = $encyptionPluginManager->get('myEncryptionPlugin')->encrypt($variable);
```

or 

```
$encrypted_value = $encryptionConfiguration->encrypt($variable);
```

**Comment by nerdstein** [comment]
@damontgomery ok, i'll see if i can make this more straight forward

**Comment by nerdstein** [comment]
One consideration is around Keys - encryption instances need keys and there is some awkardness here since we do not want to store Key-based config within code

**Comment by nerdstein** [comment]
This is done, PR #48
