### ISSUE TITLE
Key management changes

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#50]
There are two really important scenarios to consider.

1. If a key value changes
2. If a default key changes

Key is naive - it assumes someone knows how to invoke its service.

Encrypt is less naive - it references a key instance within it's Encryption Profiles. We may need to store or reference a specific revision of a Key entity.

We also should consider a "key change" service that decrypts a string with one Encryption Profile and encrypts the string with a second Encryption Profile.

**Comment by nerdstein** [comment]
CC: @EclipseGc  - need to discuss entity level revisions with you.

**Comment by nerdstein** [comment]
@rlhawk can you post about the Key scaffolding that supports this now?

**Comment by rlhawk** [comment]
@nerdstein Key adds a Form API element called `key_select` that behaves like a select element, but that is populated with available keys as `#options`. This allows module developers to easily add a key field to a settings form, like this:
```
$form['secret_key'] = [
  '#type' => 'key_select',
  '#title' => $this->t('Secret key'),
];
```
There are a couple of additional properties that can be used:
- `#key_filters` An array of filters to apply to the list of keys. Currently, filtering is quite basic, though it will be improved. You can filter on key type and/or key provider. Examples:
  - `#key_filters = ['type' => 'mailchimp']` This would only display MailChimp keys.
  - `#key_filters = ['provider' => 'file']` This would only display keys that use the File key provider.
  - `#key_filters = ['type' => 'mailchimp', 'provider' => 'file']` This would only display MailChimp keys that use the File key provider.
- `#key_description` This is a boolean value that determines if information about keys is added to the element's description. It is `TRUE` by default and it prepends the description with the following text (with a link to the add key form):

  ```
  Choose an available key. If the desired key is not listed, create a new key.
  ```

  This can disabled by setting `#key_description` to `FALSE`.

Key does not currently have any support for entity revisions and it relies on the user to be sure that a key is properly defined for whatever purpose it is needed. I have plans to add additional warnings and extra steps that would be required to change or delete a key.

**Comment by rlhawk** [comment]
Key provides the ability for plugins to add extra warnings when editing or deleting a key. Encrypt can do the same for profiles. Eventually, if we determine a good way for registering key usage and encrypt profile usage, we can a better user experience.
