### ISSUE TITLE
Make "default" a reserved word for the Key machine name

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#51]
Default cannot be used as a key's machine name

**Comment by rlhawk** [comment]
Doesn't this issue belong in Key instead of Encrypt? But is it even needed at all, since a default key isn't automatically created?

**Comment by nerdstein** [comment]
@rlhawk yes it should be in Key - I was spitballing during development. 

I am going to close this issue, you are right.
