### ISSUE TITLE
Enforce sizes of keys within Encryption Methods and/or Encryption Profiles

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#56]
Exception Warning    McryptAES256Encry   47 Drupal\encrypt\Plugin\EncryptionMet
    mcrypt_encrypt(): Key of size 17 not supported by this algorithm. Only keys
    of sizes 16, 24 or 32 supportedmcrypt_encrypt('rijndael-256', 'test this
    key out', 'S|9/_&gt;&amp;Ysu', 'ecb', '')
    Drupal\encrypt\Plugin\EncryptionMethod\McryptAES256Encryption->encrypt('S|9/_&gt;&amp;Ysu',
    'test this key out')
    Drupal\encrypt\EncryptService->encrypt('S|9/_&gt;&amp;Ysu')
    Drupal\encrypt\Tests\EncryptEncryptDecryptTest->testDefaultEncryptDecrypt()
    Drupal\simpletest\TestBase->run(Array)
    simpletest_script_run_one_test('1',
    'Drupal\encrypt\Tests\EncryptEncryptDecryptTest')

Need to do two things:

1. Enforce key lengths for mcrypt via UI

2. Update tests to ensure the fake keys used are 16, 24, or 32 chars

**Comment by rlhawk** [comment]
This has been replaced by #73.
