### ISSUE TITLE
Don't create profile automatically

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#57]
I've previously expressed the opinion that we shouldn't create a profile automatically when Encrypt is installed. I still think that's the case and I'd like to be clear about my arguments:

- Ideally, all encryption methods will be created by a submodule, so that site administrators can specifically choose what sorts of encryption methods are available on their site by enabling or disabling submodules. If there's an automatically-created profile, there will need to be a method that is always available, so it can be used for the profile, which prevents admins from having that control. They could alter the form,  but that feels like a less desirable solution.
- Creating a profile automatically is likely to leave the profile in an unusable state, since it's possible that a default key will not have been set. The user still would need to go the Encrypt profile edit page and select a key. So why not just require them to create the profile themselves to begin with? It's not very helpful to have one created for you if it's not fully functional.
- It's important when dealing with something as critical as encryption that site administrators are aware of, and fully understand, every aspect of how their data is being encrypted, where the key is, etc. Each part of the process should be completely intentional and thought out. Having anything happen automatically undermines that goal.
- The Drupal 7 version of Encrypt has an automatically-created default profile, but it's only necessary to stay backward compatible with modules that originally integrated with Encrypt before profiles were introduced in version 2.0. Thankfully, we don't need to worry about that for the Drupal 8 version.

**Comment by nerdstein** [comment]
Done

**Comment by nerdstein** [comment]
Will be in next PR
