### ISSUE TITLE
Remove PHPSecLib encryption method

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#69]
We are not going to be bundling any encryption methods with Encrypt (for more information, see #60), so the PHPSecLib method should be removed from the project.

**Comment by svendecabooter** [comment]
Is there a use case for turning it into a separate contrib module? Or should it just be removed altogether?
If we keep it around, using it should be discouraged, in favor of a module that uses the Defuse PHP Encryption library.

**Comment by svendecabooter** [comment]
I created a project for this module on drupal.org:
https://www.drupal.org/project/encrypt_seclib

I added warnings about using the module, and recommend following best practices (see https://github.com/d8-contrib-modules/encrypt/issues/79).

**Comment by svendecabooter** [comment]
PHPSecLib is removed now.
