### ISSUE TITLE
$options = array() of encrypt interface should be settings form for plugin instances

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/encrypt#7]
Ties to Encryption entity. Entity should have settings. Settings should be pulled in from the EntityMethod plugin.

**Comment by nerdstein** [comment]
Plugin could have it's own settings defined.

Use AJAX in settings form to bring in plugin form when selecting EncMethod. 

Change schema.yml for encMethod settings wildcard pulled from plugin

**Comment by nerdstein** [comment]
The solution for this is to build a settings form into the plugin and a custom schema per plugin type.

Upon selecting the enc method from AJAX via the settings form, the plugin settings will be brought in and stored with the settings for behavioral purposes.

**Comment by rlhawk** [comment]
I'm not exactly clear on the specifics of this issue, but I want to point out that in the Drupal 7 version of Encrypt, settings and options are different things. Settings are user-selected configuration, while options are meta information about the encrypted data. For instance, options could hold the initialization vector or HMAC. Perhaps "options" is not a good name for that information.

**Comment by nerdstein** [comment]
These can be baked into settings form of submodules, we have not run into a case where we need "settings" for encryption yet. Closing this
