### ISSUE TITLE
Add a simple encryption method for tests to use

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#70]
Since Encrypt will not include any bundled encryption methods, we will need to have some sort of simple method for tests to use. It doesn't even need to actually involve encryption; it just needs to modify a plaintext value in a reversible way. I propose a basic Rot13 method, because it will fulfill that need and will be easy to write.

**Comment by svendecabooter** [comment]
See also https://github.com/d8-contrib-modules/encrypt/pull/83

**Comment by svendecabooter** [comment]
The simple test EncryptionMethod has been merged in.
It works fine for the current tests.
