### ISSUE TITLE
Implement plugin collection for encryption method plugin type

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#72]
The encryption profile configuration entity should take advantage of the benefits of plugin collections by adding a plugin collection for the encryption method plugin type. Key already does this for its three plugin types, so the code can largely be copied from Key.

**Comment by svendecabooter** [comment]
See https://github.com/d8-contrib-modules/encrypt/pull/100 - this still needs review.

**Comment by rlhawk** [comment]
With #103, this is complete.
