### ISSUE TITLE
Allow encryption method to define support for key type and key type settings

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#73]
An encryption method should be able to indicate what key sizes it supports. This would be defined in an annotation field as an array of values. This could be then be used to filter the list of keys to only display keys that match one of those sizes. It could also be used for validation on form submission.

The only key type plugin that currently defines a key size is the AES Encryption type. The field name in its settings is "key_size". We can specify that any other defined key types should use that field name to allow filtering of keys by size, within Encrypt or elsewhere.

It's possible that we may wish we had a more generic option for defining requirements for keys, but size is important enough that I think it's fine to break it out and define it separately.

**Comment by rlhawk** [comment]
I renamed this because it's not just the key size (a setting of the key type) we're concerned about. It's the key type itself. For instance, an encryption method that uses AES should be able to indicate that only keys of that type ("aes_encryption") should be available, and if the key size it needs is 256 bits, it should be able to indicate that as well.

**Comment by rlhawk** [comment]
A consideration, with regard to key size, is that Encrypt will need to be more flexible in how supported key sizes can be defined. So far, we've discussed specific sizes, such as 128 bits, 192 bits, and 256 bits, since those are the sizes that AES supports. 

However, other ciphers have different key size requirements that are not so specific. Blowfish, for instance, supports keys between 32 bits and 448 bits. How can we allow an encryption method to indicate that it will accept a range like that, will still allowing the definition of the small number of sizes that other ciphers accept?

**Comment by svendecabooter** [comment]
This functionality has been merged in.
