### ISSUE TITLE
Ensure proper update of settings on AJAX reload

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#74]
The encryption method settings should behave as follows when an AJAX reload is triggered by a change in encryption method:

- If the newly selected method is not the original method (if the profile is being edited), clear the settings
- If the newly selected method is the original method, use the original settings, as defined when the form first loaded

The Key module currently implements this functionality for two of its plugins, key type and key provider, so it can be used as a resource.

**Comment by svendecabooter** [comment]
The current AJAX functionality seems to work as required.
Can you check if this is still relevant?

**Comment by rlhawk** [comment]
It is still relevant in cases where an encryption method has settings.

**Comment by svendecabooter** [comment]
This has been taken care of in https://github.com/d8-contrib-modules/encrypt/pull/103
Please reopen if this should not be sufficient
