### ISSUE TITLE
Add information about status of profile

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#75]
The current status of an encryption profile should be added to the profile listing page. It would be based on requirements such as:

- The key value can be retrieved
- The key value is a size that the encryption method supports
- All dependences of the encryption method have been met (any external libraries are available, for example)

This information could also be added as a Drupal message on the profile edit page.

**Comment by rlhawk** [comment]
We may want to discuss the possibility that running a status check on all profiles on the profiles page could be burdensome—if a user has 100+ profiles, for instance. We could even add a setting that would allow users to disable the status check. That could be useful anyway, in the instance where a user doesn't want their keys retrieved whenever they load the profiles page.

**Comment by svendecabooter** [comment]
This functionality is merged into master now.
