### ISSUE TITLE
Update simple tests

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#77]
Simple tests will need to be refactored and/or rewritten to support the architectural changes planned for Encrypt.

**Comment by svendecabooter** [comment]
See also https://github.com/d8-contrib-modules/encrypt/pull/83

**Comment by svendecabooter** [comment]
The tests in the PR mentioned above should be expanded.
On hold for now, until the PR is merged.

**Comment by svendecabooter** [comment]
Tests have been updated.

**Comment by svendecabooter** [comment]
Closing this issue, since we have now working tests.
Obviously they would need to be updated when new or changed functionality is added to the codebase, but that should be handled in those issues.
