### ISSUE TITLE
Add key type plugin for AES Encryption

### ISSUE THREAD

**Issue by rlhawk** [d8-contrib-modules/encrypt#80]
The AES Encryption plugin is in the process of being removed from Key, but it will have a new home in Encrypt. It will extend the generic Encryption key type and customize the `#options` in the `key_size` setting, allowing only three sizes: 128, 192, and 256. I suggest that we make the default size 256.

**Comment by svendecabooter** [comment]
Dependencies in Key module:
* https://www.drupal.org/node/2664910
* https://www.drupal.org/node/2664912

**Comment by svendecabooter** [comment]
Fixed

**Comment by svendecabooter** [comment]
Actually, it might give conflicts with Key module, because both modules now provide an AES KeyType plugin... But we should followup in the Key issue queue to get that removed in the next version of Key.
