### ISSUE TITLE
Define first release blockers

### ISSUE THREAD

**Issue by svendecabooter** [d8-contrib-modules/encrypt#97]
Hi,

I feel the code base of this module is approaching a state where a first alpha release could be created.
I've created a Github milestone and tagged the issues that I think are blocking this release in the queue with it.

Please chime in if you feel some issues aren't blocking the release, or if others are, that haven't been put in that milestone.

@nerdstein @rlhawk could you give your opinion?

**Comment by svendecabooter** [comment]
Probably also important to note that there are still a few patches that need to get into the Key module as well, for the first release of Encrypt to work properly.

**Comment by svendecabooter** [comment]
I think all issues that were defined as requirements for a first release / move to drupal.org are now solved. Let me know if you agree that the module is a pretty good state for a first alpha release, so we can have people testing it out and reporting potential issues with it.

**Comment by nerdstein** [comment]
I agree, yes. I'll be moving it today.

There will absolutely be issues uncovered. I'm confident this collaboration can occur (and should) with the visibility of the community. 

@svendecabooter thanks for your efforts here.
